// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/context/repo.go

// Package mock_context is a generated GoMock package.
package mock_context

import (
	reflect "reflect"

	git "github.com/gogs/git-module"
	gomock "github.com/golang/mock/gomock"
	db "github.com/ivis-yoshida/gogs/internal/db"
)

// MockAbstructCtxRepository is a mock of AbstructCtxRepository interface.
type MockAbstructCtxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAbstructCtxRepositoryMockRecorder
}

// MockAbstructCtxRepositoryMockRecorder is the mock recorder for MockAbstructCtxRepository.
type MockAbstructCtxRepositoryMockRecorder struct {
	mock *MockAbstructCtxRepository
}

// NewMockAbstructCtxRepository creates a new mock instance.
func NewMockAbstructCtxRepository(ctrl *gomock.Controller) *MockAbstructCtxRepository {
	mock := &MockAbstructCtxRepository{ctrl: ctrl}
	mock.recorder = &MockAbstructCtxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAbstructCtxRepository) EXPECT() *MockAbstructCtxRepositoryMockRecorder {
	return m.recorder
}

// GetBranchName mocks base method.
func (m *MockAbstructCtxRepository) GetBranchName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBranchName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetBranchName indicates an expected call of GetBranchName.
func (mr *MockAbstructCtxRepositoryMockRecorder) GetBranchName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBranchName", reflect.TypeOf((*MockAbstructCtxRepository)(nil).GetBranchName))
}

// GetCommitId mocks base method.
func (m *MockAbstructCtxRepository) GetCommitId() *git.SHA1 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitId")
	ret0, _ := ret[0].(*git.SHA1)
	return ret0
}

// GetCommitId indicates an expected call of GetCommitId.
func (mr *MockAbstructCtxRepositoryMockRecorder) GetCommitId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitId", reflect.TypeOf((*MockAbstructCtxRepository)(nil).GetCommitId))
}

// GetDbRepo mocks base method.
func (m *MockAbstructCtxRepository) GetDbRepo() db.AbstructDbRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDbRepo")
	ret0, _ := ret[0].(db.AbstructDbRepository)
	return ret0
}

// GetDbRepo indicates an expected call of GetDbRepo.
func (mr *MockAbstructCtxRepositoryMockRecorder) GetDbRepo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDbRepo", reflect.TypeOf((*MockAbstructCtxRepository)(nil).GetDbRepo))
}

// GetRepoLink mocks base method.
func (m *MockAbstructCtxRepository) GetRepoLink() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepoLink")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRepoLink indicates an expected call of GetRepoLink.
func (mr *MockAbstructCtxRepositoryMockRecorder) GetRepoLink() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepoLink", reflect.TypeOf((*MockAbstructCtxRepository)(nil).GetRepoLink))
}

// GetTreePath mocks base method.
func (m *MockAbstructCtxRepository) GetTreePath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTreePath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTreePath indicates an expected call of GetTreePath.
func (mr *MockAbstructCtxRepositoryMockRecorder) GetTreePath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTreePath", reflect.TypeOf((*MockAbstructCtxRepository)(nil).GetTreePath))
}
