name: Deploy Develop Environment

on:
  push:
    branches:
      - 'feature/**'
      - 'workflow-test'
    paths:
      - '**.go'
      - '!**_gen.go'

jobs:
  build_docker:
    runs-on: [self-hosted, development]
    environment: development
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16.6'
    - name: set ENV
      run: |
        echo "GOBIN="$HOME"/go/bin" >> $GITHUB_ENV
        echo $GOBIN >> $GITHUB_PATH
        echo $PATH
        go env -w GOBIN=$HOME"/go/bin"
    - name: Install dependencies
      run: |
        go get -u github.com/kevinburke/go-bindata/...
        go-bindata -v
    - uses: actions/checkout@v2
      with:
        ref: $GITHUB_REF_NAME
    - name: Create *_gen.go files (3 files)
      run: |
        go generate ./internal/assets/conf/conf.go
        go generate ./internal/assets/templates/templates.go
        go generate ./internal/assets/public/public.go
    - name: Build docker image
      run: sudo docker build -t gin.rdc:${{ secrets.VER }} .
  deploy:
    runs-on: [self-hosted, development]
    needs: build_docker
    environment: development
    steps:
      - name: Set Env
        run: |
          rm -f .env
          touch .env
          echo "VER="${{ secrets.VER }} >> .env
          echo "POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo "POSTGRES_DB_NAME="${{ secrets.POSTGRES_DB_NAME }} >> .env
          echo "DB_SERVER_PORT="${{ secrets.DB_SERVER_PORT }} >> .env
          echo "DB_CONTAINER_PORT="${{ secrets.DB_CONTAINER_PORT }} >> .env
          echo "GIN_WEB_SEVER_PORT="${{ secrets.GIN_WEB_SEVER_PORT }} >> .env
          echo "GIN_WEB_CONTAINER_PORT="${{ secrets.GIN_WEB_CONTAINER_PORT }} >> .env
          echo "GIN_SEVER_PORT="${{ secrets.GIN_SEVER_PORT }} >> .env
          echo "GIN_CONTAINER_PORT="${{ secrets.GIN_CONTAINER_PORT }} >> .env
      - name: Run docker-compose
        run: |
          sudo docker-compose -f docker-compose.development.yml up -d
